global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: netsonar
    static_configs:
      - targets: ["netsonar:9275"]
    metrics_path: /metrics

  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://fake-targets:8080/ok
        labels:
          target_name: http-ok
          probe_type: http
          network_path: direct
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox-https
    metrics_path: /probe
    params:
      module: [http_2xx_tls]
    static_configs:
      - targets:
          - https://fake-targets:9443/ok
        labels:
          target_name: https-ok
          probe_type: http
          network_path: direct
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackbox-exporter:9115
